import Head from 'next/head'
import Image from 'next/image'
import { useRef } from 'react'
import Banniere from '../components/Banniere/Banniere'
import Bio from '../components/Bio/Bio'
import Contact from '../components/Contact/Contact'
import Education from '../components/Education/Education'
import Experience from '../components/Experience/Experience'
import Nav from '../components/Nav/Nav'
import styles from '../styles/Home.module.css'

export default function Home() {
  let story, tools, educ, xp, work, contact
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav refs={[story, tools, educ, xp, work, contact]} scroll={scrollToRef}/>
      <Banniere/>
      <Bio/>
      <Education/>
      <Experience/>
      <Contact/>
    </div>
  )
}

function scrollToRef () {

}
