import Head from 'next/head'
import Image from 'next/image'
import Banniere from '../components/Banniere/Banniere'
import Bio from '../components/Bio/Bio'
import Education from '../components/Education/Education'
import Experience from '../components/Experience/Experience'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Banniere/>
      <Bio/>
      <Education/>
      <Experience/>
    </div>
  )
}
